# Generated by Django 2.1.5 on 2019-03-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_detalle_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='lugar',
        ),
    ]
