# Generated by Django 2.1.5 on 2019-03-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_programa_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='cupoMax',
            field=models.IntegerField(default=20, max_length=4),
            preserve_default=False,
        ),
    ]
